package org.perftester.process

import java.io.File

object Compiler extends App {
  val lib = "C:\\Users\\dev\\scalacBuildCache\\d1b745c2e97cc89e5d26b8f5a5696a2611c01af7\\lib\\"
  val classPath =
    s"${lib}jline.jar;${lib}scala-compiler-doc.jar;${lib}scala-compiler.jar;${lib}scala-library.jar;${lib}scala-reflect.jar;${lib}scala-repl-jline-embedded.jar;${lib}scala-repl-jline.jar;${lib}scala-swing_2.12-2.0.0.jar;${lib}scala-xml_2.12-1.0.6.jar;${lib}scalap.jar"
  val params = List("-Xmx256M",
                    "-Xms32M",
                    """-Dscala.home="C:\PROGRA~2\scala\bin\.."""",
                    """-Denv.emacs="" """,
                    "-Dscala.usejavacp=true")
  val files = List(
    "S:/scala/akka/akka-actor/src/main/scala/akka/AkkaException.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/Done.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/Main.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/NotUsed.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/AbstractActor.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/AbstractFSM.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/AbstractProps.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/Actor.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/ActorCell.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/ActorDSL.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/ActorPath.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/ActorRef.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/ActorRefProvider.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/ActorSelection.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/ActorSystem.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/Address.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/CoordinatedShutdown.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/Deployer.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/DynamicAccess.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/Extension.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/FaultHandling.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/FSM.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/IndirectActorProducer.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/LightArrayRevolverScheduler.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/package.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/Props.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/ReflectiveDynamicAccess.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/RepointableActorRef.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/Scheduler.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/Stash.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/TypedActor.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/UntypedActor.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/UntypedActorWithStash.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/dsl/Creators.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/dsl/Inbox.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/dungeon/Children.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/dungeon/ChildrenContainer.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/dungeon/DeathWatch.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/dungeon/Dispatch.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/dungeon/FaultHandling.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/dungeon/ReceiveTimeout.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/actor/setup/ActorSystemSetup.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/dispatch/AbstractDispatcher.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/dispatch/BalancingDispatcher.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/dispatch/BatchingExecutor.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/dispatch/CachingConfig.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/dispatch/Dispatcher.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/dispatch/Dispatchers.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/dispatch/Future.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/dispatch/Mailbox.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/dispatch/Mailboxes.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/dispatch/PinnedDispatcher.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/dispatch/ThreadPoolBuilder.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/dispatch/sysmsg/SystemMessage.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/event/ActorClassificationUnsubscriber.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/event/AddressTerminatedTopic.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/event/DeadLetterListener.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/event/EventBus.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/event/EventStream.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/event/EventStreamUnsubscriber.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/event/LoggerMailbox.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/event/Logging.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/event/LoggingReceive.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/event/japi/EventBusJavaAPI.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/DirectByteBufferPool.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/Dns.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/DnsProvider.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/Inet.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/InetAddressDnsProvider.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/InetAddressDnsResolver.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/IO.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/SelectionHandler.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/SimpleDnsCache.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/SimpleDnsManager.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/Tcp.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/TcpConnection.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/TcpIncomingConnection.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/TcpListener.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/TcpManager.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/TcpOutgoingConnection.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/Udp.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/UdpConnected.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/UdpConnectedManager.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/UdpConnection.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/UdpListener.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/UdpManager.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/UdpSender.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/io/WithUdpSend.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/japi/JavaAPI.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/japi/function/Function.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/japi/pf/CaseStatements.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/pattern/AskSupport.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/pattern/BackoffOnRestartSupervisor.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/pattern/BackoffOptions.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/pattern/BackoffSupervisor.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/pattern/CircuitBreaker.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/pattern/FutureTimeoutSupport.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/pattern/GracefulStopSupport.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/pattern/package.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/pattern/Patterns.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/pattern/PipeToSupport.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/pattern/PromiseRef.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/pattern/extended/package.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/Balancing.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/Broadcast.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/ConsistentHash.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/ConsistentHashing.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/Listeners.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/MurmurHash.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/OptimalSizeExploringResizer.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/Random.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/Resizer.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/RoundRobin.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/RoutedActorCell.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/RoutedActorRef.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/Router.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/RouterConfig.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/ScatterGatherFirstCompleted.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/SmallestMailbox.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/routing/TailChopping.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/serialization/Serialization.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/serialization/SerializationExtension.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/serialization/SerializationSetup.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/serialization/Serializer.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/BoundedBlockingQueue.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/BoxedType.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/ByteIterator.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/ByteString.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/ClassLoaderObjectInputStream.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/Collections.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/HashCode.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/Helpers.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/Index.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/JavaDurationConverters.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/LineNumbers.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/LockUtil.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/OptionVal.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/PrettyByteString.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/PrettyDuration.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/Reflect.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/SerializedSuspendableExecutionContext.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/StablePriorityQueue.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/SubclassifiedIndex.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/Timeout.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/TokenBucket.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/TypedMultiMap.scala",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/Unsafe.java",
    "S:/scala/akka/akka-actor/src/main/scala/akka/util/WildcardIndex.scala"
  )

  def allParams(i: Int) =
    List(
      "-d",
      "z:",
      "-classpath",
      "C:\\Users\\dev\\.ivy2\\cache\\org.scala-lang.modules\\scala-java8-compat_2.12\\bundles\\scala-java8-compat_2.12-0.8.0.jar;C:\\Users\\dev\\.ivy2\\cache\\com.typesafe\\config\\bundles\\config-1.3.1.jar;C:\\Users\\dev\\.m2\\repository\\com\\typesafe\\akka\\akka-actor_2.12\\2.5.1\\akka-actor_2.12-2.5.1.jar",
      "-sourcepath",
      "S:\\scala\\akka\\akka-actor\\src\\main\\java;S:\\scala\\akka\\akka-actor\\src\\main\\scala",
      "-Yprofile-destination",
      s"S:\\scala\\test\\results\\mike\\COMPILER\\${i}_run_new.csv"
    ) ++ files

  for (vm <- 1 to 20) {
    val parent = new Parent(new File("."), None, classPath.split(";").toList, params)
    for (cycle <- 1 to 100) {
      parent.doRun("scala.tools.nsc.Main", allParams(vm): _*)
      parent.doGc()
    }
    parent.doExit()
  }

}
