package shapeless

import scala.Predef._

/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
  /** The value is "2.3.3". */
  val version: String = "2.3.3"
  /** The value is "2.13.0-M4". */
  val scalaVersion: String = "2.13.0-M4"
  /** The value is scala.Some("f185aa38b59d34529ef9e4c2dc51e667365376ce"). */
  val gitHeadCommit: scala.Option[String] = scala.Some("f185aa38b59d34529ef9e4c2dc51e667365376ce")
  /** The value is "2018-06-25 10:53:04.978". */
  val builtAtString: String = "2018-06-25 10:53:04.978"
  /** The value is 1529923984978L. */
  val builtAtMillis: scala.Long = 1529923984978L
  override val toString: String = {
    "version: %s, scalaVersion: %s, gitHeadCommit: %s, builtAtString: %s, builtAtMillis: %s".format(
      version, scalaVersion, gitHeadCommit, builtAtString, builtAtMillis
    )
  }
}
